import mongoose from "mongoose";

const dailyReadinessSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },

    date: {
      type: Date,
      required: true
    },

    // Manual inputs (optional for auto/AI)
    sleepHours: {
      type: Number,
      min: 0,
      max: 24
    },

    sleepQuality: {
      type: String,
      enum: ["poor", "average", "good"],
      default: "average"
    },

    stressLevel: {
      type: String,
      enum: ["low", "medium", "high"]
    },

    subjectiveFeeling: {
      type: String,
      enum: ["fresh", "normal", "tired"]
    },

    restingHeartRate: {
      type: Number
    },

    hydrationLevelPercent: {
      type: Number,
      min: 0,
      max: 100,
      default: 70
    },

    sorenessAreas: {
      type: [String],
      default: []
    },

    // Output
    readinessScore: {
      type: Number,
      min: 0,
      max: 100
    },

    readinessCategory: {
      type: String,
      enum: ["low", "moderate", "high"]
    },

    autoGenerated: {
      type: Boolean,
      default: false
    },

    source: {
      type: String,
      enum: ["manual", "auto", "ai"],
      default: "manual"
    }
  },
  {
    timestamps: true
  }
);

dailyReadinessSchema.index({ userId: 1, date: 1 }, { unique: true });

export default mongoose.model("DailyReadiness", dailyReadinessSchema);

